import type { Story } from "@/lib/story";

export type DemoStory = Story;
export { formatViews } from "@/lib/story";

const img = (id: string, w = 1200) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=80`;

export const DEMO_STORIES: DemoStory[] = [
  {
    id: "1",
    href: "/security/niger-can-demands-security-at-worship-centres",
    category: "Security",
    categorySlug: "security",
    title:
      "Niger CAN demands tighter security at worship centres after mass abduction",
    dek: "Church leaders urge coordinated patrols across the state as communities wait for safe return of abductees.",
    imageUrl: img("photo-1586339949916-3e9457bef6d3", 1800),
    imageAlt: "People gathered outdoors at a community meeting",
    publishedLabel: "3 hours ago",
    viewCount: 1284,
    byline: "Egigogo Reporter, Minna",
    type: "news",
    body: [
      "Leaders of the Christian Association of Nigeria in Niger State have called for heightened security around places of worship following a wave of abductions that has left congregations on edge.",
      "Speaking in Minna, the association urged security agencies to coordinate patrols with community vigilance groups, especially ahead of weekend services.",
      "Families of those still missing asked the public to share credible tips while cautioning against unverified rumours on social media.",
    ],
  },
  {
    id: "2",
    href: "/agriculture/women-graduates-zinariya-minna-empowerment",
    category: "Agriculture",
    categorySlug: "agriculture",
    title: "Five hundred women graduate under Zinariya Minna skills programme",
    dek: "Catering and cosmetology trainees in Shiroro mark a third cohort as organisers call for startup kits.",
    imageUrl: img("photo-1464226184884-fa280b87c309", 1800),
    imageAlt: "Rows of green crops under open sky",
    publishedLabel: "Yesterday",
    viewCount: 892,
    byline: "YM Bina",
    type: "news",
    body: [
      "Five hundred women have completed training in catering and cosmetology under the Zinariya Minna empowerment drive, organisers said at a graduation in Gwada.",
      "Officials described the programme as a response to household poverty and asked partners to support graduates with startup kits.",
    ],
  },
  {
    id: "3",
    href: "/politics/apc-niger-call-for-unity-and-reconciliation",
    category: "Politics",
    categorySlug: "politics",
    title: "Stakeholders urge APC leadership in Niger to choose unity over division",
    dek: "An open appeal for a broad stakeholders’ meeting ahead of 2027, framed as reconciliation not attack.",
    imageUrl: img("photo-1529107386315-e1a2ed48a620", 1800),
    imageAlt: "Assembly hall with seated audience",
    publishedLabel: "2 days ago",
    viewCount: 2103,
    byline: "Comr. Amb. Suleiman Abdullahi",
    type: "opinion",
    body: [
      "The time has come for stakeholders of the All Progressives Congress in Niger State to put aside personal differences and work for the collective interest of the party.",
      "This is a call for dialogue, forgiveness and a fresh beginning — not an attack on any leader.",
    ],
  },
  {
    id: "4",
    href: "/health/kano-committee-diphtheria-response",
    category: "Health",
    categorySlug: "health",
    title: "Kano sets up special committee to strengthen diphtheria response",
    dek: "State officials say surveillance and community sensitisation will be stepped up in high-risk local governments.",
    imageUrl: img("photo-1579684385127-1ef15d508118", 1200),
    imageAlt: "Healthcare worker in a clinic setting",
    publishedLabel: "4 hours ago",
    viewCount: 640,
    byline: "National Desk",
    type: "news",
  },
  {
    id: "5",
    href: "/sports/niger-tornadoes-edge-enyimba",
    category: "Sports",
    categorySlug: "sports",
    title: "Niger Tornadoes edge Enyimba 2–1 as SWAN honours stadium contractor",
    dek: "A late strike sealed the points in Minna while football writers recognised work on the state stadium.",
    imageUrl: img("photo-1574629810360-7efbbe195018", 1200),
    imageAlt: "Football match under stadium lights",
    publishedLabel: "6 hours ago",
    viewCount: 1502,
    byline: "Sports Desk",
    type: "news",
  },
  {
    id: "6",
    href: "/business/minna-market-traders-seek-credit",
    category: "Business",
    categorySlug: "business",
    title: "Minna traders seek cheaper credit as food prices stay elevated",
    dek: "Market leaders say working capital remains the biggest barrier for small wholesalers.",
    imageUrl: img("photo-1556740749-887f6717d7e4", 1200),
    imageAlt: "Busy open-air market stalls",
    publishedLabel: "1 day ago",
    viewCount: 411,
    byline: "Business Desk",
    type: "news",
  },
  {
    id: "7",
    href: "/features/voices-from-shiroro-farming-season",
    category: "Community",
    categorySlug: "community",
    title: "Voices from Shiroro: farming families on a difficult planting season",
    dek: "A feature on rain patterns, security fears and the quiet resolve of rural households.",
    imageUrl: img("photo-1500382017468-9049fed747ef", 1200),
    imageAlt: "Open field under a wide sky",
    publishedLabel: "3 days ago",
    viewCount: 730,
    byline: "Features Desk",
    type: "feature",
  },
  {
    id: "8",
    href: "/investigations/how-a-local-contract-raised-questions",
    category: "Governance",
    categorySlug: "governance",
    title: "How a local contract in Niger raised questions about procurement transparency",
    dek: "Documents and interviews point to gaps between award notices and delivery timelines.",
    imageUrl: img("photo-1450101499163-c8848c66ca85", 1200),
    imageAlt: "Documents and a pen on a desk",
    publishedLabel: "5 days ago",
    viewCount: 3201,
    byline: "Investigations",
    type: "investigative",
  },
  {
    id: "9",
    href: "/technology/atbuth-mobile-app-digital-healthcare",
    category: "Technology",
    categorySlug: "technology",
    title: "Teaching hospital unveils mobile app to ease digital healthcare access",
    dek: "Officials say the tool will help patients book and follow up without long queues.",
    imageUrl: img("photo-1576091160399-112ba8d25d1d", 1200),
    imageAlt: "Person using a smartphone",
    publishedLabel: "1 week ago",
    viewCount: 980,
    byline: "Tech Desk",
    type: "news",
    hasVideo: true,
  },
  {
    id: "10",
    href: "/education/exchange-programme-entrance-exams",
    category: "Education",
    categorySlug: "education",
    title: "Exchange programme entrance exams hold for selected secondary schools",
    dek: "Candidates sat papers aimed at overseas study pathways, organisers confirmed.",
    imageUrl: img("photo-1509062522246-3755977927d7", 1200),
    imageAlt: "Students in a classroom",
    publishedLabel: "1 week ago",
    viewCount: 554,
    byline: "Education Desk",
    type: "news",
  },
  {
    id: "11",
    href: "/national/tinubu-departs-abuja-annual-vacation",
    category: "National",
    categorySlug: "national",
    title: "President departs Abuja for three-week annual vacation",
    dek: "A brief state house note confirmed travel plans and acting arrangements.",
    imageUrl: img("photo-1540962351504-1695c1ced6b7", 1200),
    imageAlt: "Airplane on a runway",
    publishedLabel: "8 hours ago",
    viewCount: 4400,
    byline: "National Desk",
    type: "news",
  },
  {
    id: "12",
    href: "/entertainment/minna-cultural-night-returns",
    category: "Entertainment",
    categorySlug: "entertainment",
    title: "Minna cultural night returns with music and local fashion showcases",
    dek: "Organisers promise a family-friendly evening on the state capital calendar.",
    imageUrl: img("photo-1514525253161-7a46d19cd819", 1200),
    imageAlt: "Concert lights and crowd",
    publishedLabel: "4 days ago",
    viewCount: 301,
    byline: "Entertainment Desk",
    type: "news",
  },
];

